### ISSUE TITLE
Unable to set large icon on push notifications for Android

### ISSUE THREAD

**Issue by EJJSharpe** [exponea/exponea-react-native-sdk#101]
We're looking to add add custom large icons to our Android notification. You can see this with the large google icon shown on the right hand side of the push notification in the photo below:
<img src="https://github.com/exponea/exponea-react-native-sdk/assets/64373806/6eac7221-055b-4e26-ab41-ed14b9b37b4c" width="250"/>

As far as I can tell the handleRemoteMessage method [here](https://github.com/exponea/exponea-android-sdk/blob/0fc1192ab5d49d96393b3335aa2d150b6373ceb9/sdk/src/main/java/com/exponea/sdk/manager/FcmManagerImpl.kt) is exposed to the React Native side and the large icon is never set in the notification builder. 

Can you confirm whether we are able to set a large icon through Exponea?

**Comment by adam1929** [comment]
Hi @EJJSharpe thank you for question.
Unfortunately, SDK is showing icon/image in way you see.
You may send `image` in notification payload and BigPictureStyle will be used.
You may defined `pushIcon` in SDK configuration and `setSmallIcon` will be set upon notification.
For further changes, you need to provide your own "Notification Factory" implementation; there are lot of possibilities of styling and so on.
