### ISSUE TITLE
should "Exponea.configure()" not be marked with await?

### ISSUE THREAD

**Issue by Adnan-Bacic** [exponea/exponea-react-native-sdk#104]
according to the types it returns `Promose<void>`, but the documention shows you have to write it as:

`Exponea.configure(configuration);`

instead of

`await Exponea.configure(configuration);`

am i correct to believe it should have await in front?

**Comment by adam1929** [comment]
No.
You can use `await` only for `async` methods but `Exponea.configure` is not.
Promise return type is defined by ReactNative for native-plugins, it is a way of RN-native communication.
If still questionable, why Promise 'was choose to be' return type by RN:
- it could be used for async method (what we are not using but could not be so either)
- it simplifies rn<->native communication, also unifies async and sync methods
- you are able to define success and failure flow in single response without try-catch definitions.
All these reasons are subjective opinion, each developer could have own. We decided to keep mainstream and recommended ways.
