### ISSUE TITLE
is there something that can make configuring exponea throw an expection?

### ISSUE THREAD

**Issue by Adnan-Bacic** [exponea/exponea-react-native-sdk#105]
the example code to configure exponea:

```
async function configureExponea(configuration: Configuration) {
  try {
    if (!await Exponea.isConfigured()) {
      Exponea.configure(configuration)
    } else {
      console.log("Exponea SDK already configured.")
    }
  } catch (error) {
    console.log(error)
  }
}
```

ive been playing around with this, but i cant seem to "force" an exception. i want to enter the catch block, but it never does. so i was curious to if there is something which can trigger an exception so we enter the catch block. ive tried removing some of the required parameters but it does not trigger an exception.

**Comment by adam1929** [comment]
It seems complex and more paranoid way rather than reasonable, but still recommended. Our mantra is to create stable library but we may make a mistake. Therefore this try-catch wrap is recommended way to log error message rather then cause crash of your app.
