### ISSUE TITLE
iOS - missing example on how to configure push notifications without ExponeaRNAppDelegate

### ISSUE THREAD

**Issue by dannyBies** [exponea/exponea-react-native-sdk#108]
Hi!

I'm looking at integrating this SDK into my Expo react-native app. As Expo is currently not supported by this SDK I'm adding support for this in my own app by creating a [Config Plugin](https://docs.expo.dev/config-plugins/introduction/).

I've been following the documentation and most of it has been pretty easy to set up. However, when looking at the [iOS documentation for push notifications](https://github.com/exponea/exponea-react-native-sdk/blob/master/documentation/PUSH_IOS.md) I'm unsure on what I need to do to add support.

This is the native code Expo generates for me with `npx expo prebuild`
`AppDelegate.h`:
```AppDelegate.h
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import <Expo/Expo.h>
@interface AppDelegate : EXAppDelegateWrapper

@end
```

`AppDelegate.mm`:
```AppDelegate.mm
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTLinkingManager.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"main";

  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@".expo/.virtual-metro-entry"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [super application:application openURL:url options:options] || [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  BOOL result = [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler] || result;
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  return [super application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  return [super application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

@end
```

I'm not able to use the `ExponeaRNAppDelegate` to inherit from. The documentation mentions that this is not required:
> If you cannot/don't want to use ExponeaRNAppDelegate superclass, import ExponeaRNAppDelegate.h in AppDelegate.m and copy over the methods/add calls to Exponea to existing ones. You'll also have to set the UNUserNotificationCenter delegate and code for processing notifications to didFinishLaunchingWithOptions.

I'm not sure how to do this and I'm not able to find any examples within this repo or on github showing what needs to be done to configure this correctly.

I was wondering if it is possible to either:
1) - Add support for Expo
2) - Add an example showing how to set up push notifications without inheriting from `ExponeaRNAppDelegate`
3) - Update my sample `AppDelegate.mm` to show how this should be configured?

Thanks!

**Comment by adam1929** [comment]
Hi @dannyBies thank you for reporting
Answers:

1. I'm sorry, we currently have no plan to support Expo.
2. There is no such example; as guide said "just copy" methods (or their bodies). I think that 99% cases of this step is, that you need to extend some other AppDelegate implementation from other library or so. We are not able to tell 100% solution because of high chance of "incompatibility" with "other library" AppDelegate. It really is needed be done and validated by you as developer, if ExponeaRNAppDelagate implementation is valid for your use case.
3. I'm unable to tell exact solution for you as I don't know your usage and expected behaviour of your app. I can only "guide" you, for example of `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` you should put `[UNUserNotificationCenter currentNotificationCenter].delegate = self;` as is defined in ExponeaRNAppDelagate.m and it "should be" all what has to be done. But still, I'm not able to 100% tell if it fits your expectation and compatibility with Expo library.
