### ISSUE TITLE
None of the callbacks are called if notification doesn't open in iOS

### ISSUE THREAD

**Issue by kaystd** [exponea/exponea-react-native-sdk#11]
Hello!
In iOS (unlike Android) none of the callbacks are called if notification doesn't open and stays in notification center, or if it dismissed. Is this behavior expected, and if so, how should the application receive the data contained in this notification?

**Comment by wassil** [comment]
Hi,
that is expected behavior. You can use silent push notifications to send data into your application.

**Comment by kaystd** [comment]
Is it technically possible to take data from standard push, not silent one in that case?

**Comment by wassil** [comment]
Yes, it is possible, but it has to be done inside notification service extension and then shared with the main application e.g. using UserDefaults
