### ISSUE TITLE
Support for react native 0.73.x 

### ISSUE THREAD

**Issue by dannyBies** [exponea/exponea-react-native-sdk#113]
Hi!

React-Native 0.73 came out a couple of months ago and I would like to upgrade my project to the latest version. It looks like there is no support for 0.73 in this project? Are there any plans to support this version in the near future?

Thanks!

**Comment by adam1929** [comment]
Hi @dannyBies. Upgrade to support 0.73 will be delivered in next SDK release.
We always upgrade RN support to latest stable version available in time of SDK release.

**Comment by dannyBies** [comment]
That's great, thanks! Do you have a rough idea about when the next version will be released?

**Comment by gustafholmer** [comment]
I am also interested to know :)

**Comment by frenic** [comment]
Why is the issue closed? It's still an issue and quite an annoying one! Specially when 0.74 is on the way and this package is  **the only** package blocking us from upgrading from 0.72. C'mon speed up, pretty please!

**Comment by xcibik00** [comment]
Hi @frenic , support of newer RN version will be a part of our next release.

**Comment by frenic** [comment]
Great! That narrows it down to sometime this year, if we're lucky. You seriously need new routines for your release cycles when you're have strict version peer dependencies like this. New RN versions has to be verified and peer dependency bumped within maximum a couple of weeks. Even RN patch releases. It's outrageous that we even have to wait several months to patch our apps with security patches!

**Comment by xcibik00** [comment]
Hi @frenic, thanks for the feedback and for the patience -> we are still trying to improve and update our internal processes to be able to bring new wrapper versions more often.
We will do our best to bring it to you ASAP.

**Comment by frenic** [comment]
> Upgrade to support 0.73 will be delivered in next SDK release.

It didn't!

**Comment by xcibik00** [comment]
Hi @frenic , am so sorry that was my mistake in expression, by the "next SDK release" - was meant as in the next version (1.7.0) we are currently intensively working on - we will release it ASAP

1.6.1 was just a hotfix version, fixing only one specific issue which was crucial for PUSH notifications

Thanks for your patience

**Comment by xcibik00** [comment]
Hi guys, just would like to let you know that we already released new SDK version 1.7.0 which support RN up to 0.73.6.
Thanks for the patience!

**Comment by dannyBies** [comment]
Amazing, thanks a lot! Looking forward to integrating this next week.
