### ISSUE TITLE
Support for react-native 0.75.x and the New Architecture

### ISSUE THREAD

**Issue by dannyBies** [exponea/exponea-react-native-sdk#114]
Hi!

~~React-Native 0.74 is almost stable so I wanted to create this issue to keep track of adding support within this library.~~
React-Native 0.75 has been released since this issue has been opened.

Additionally, the RN community is working hard at making the RN ecosystem compatible with the new architecture. Is this something Bloomreach will support in the future? See https://github.com/reactwg/react-native-new-architecture/discussions/167 for more context.

**Comment by hpeinar** [comment]
React-Native 0.74 (along with Expo 51) has now been released so it would be ideal if this library would follow suite.

**Comment by roland-misica** [comment]
Hi @dannyBies, and @hpeinar 
thanks for letting us know, we will support React-Native 0.74 soon.
We are planning to support new architecture and bridgeless mode in the future.

**Comment by hpeinar** [comment]
@roland-misica any updates on this?

**Comment by xcibik00** [comment]
Hi @hpeinar, unfortunately not yet, but we have it on roadmap - so will keep you updated about the progress.
Thanks for the patience.

**Comment by dannyBies** [comment]
Is there any way for us to track progress on this and future react-native updates? 

React-Native 0.74 has been out for 2 months and the first RC was released 4 months ago. This has been the only library blocking my app from updating React-Native and Expo, which includes important security updates, features and bugfixes that we need access to.

Unfortunately this is making it hard to justify to keep using Bloomreach.

**Comment by xcibik00** [comment]
Hi @dannyBies , as I already mentioned its on our roadmap (and will be delivered probably in Q3). For more details please reach out your Bloomreach Customer Success Manager.
Thanks

**Comment by dannyBies** [comment]
If anyone is interested, I've created a fork that add support for React-Native 0.74.2. From initial testing it seems to work fine for my use-case - https://github.com/dannyBies/exponea-react-native-sdk/tree/feat/upgrade-react-native.

```npm install @dannybies/react-native-exponea-sdk@1.9.0-rc.2```

I might add my expo config plugin to this fork in the future which can be used to stay in the expo managed workflow.

**Comment by zeraphie** [comment]
> If anyone is interested, I've created a fork that add support for React-Native 0.74.2. From initial testing it seems to work fine for my use-case - https://github.com/dannyBies/exponea-react-native-sdk/tree/feat/upgrade-react-native.
> 
> `npm install @dannybies/react-native-exponea-sdk@1.9.0-rc.2`
> 
> I might add my expo config plugin to this fork in the future which can be used to stay in the expo managed workflow.

Thanks for this, the speed of react native updates has been too slow for us too 😅 worked like a charm

**Comment by dannyBies** [comment]
I've updated the issue as React-Native 0.75.x has been released by now..

**Comment by RoccoDocco** [comment]
Same here. I would like to at least update to 0.74 for now, 0.75 would be even better. The support for the latest React Native release has always been lagging behind, but two releases is a bit too much.

**Comment by xcibik00** [comment]
Hi all, just now we released new Exponea RN SDK version 1.9.0 with support for RN 0.74.5

**Comment by dannyBies** [comment]
That's great, thanks!

Any idea about when support for 0.75 will be added? (Also the first release candidate for [0.76](https://github.com/facebook/react-native/releases/tag/v0.76.0-rc.0) was released just a few hours after Exponea 1.9.0 😅  )

**Comment by xcibik00** [comment]
Hi @dannyBies , not yet but we will keep you updated about the timeline, we would like to do Exponea RN SDK updates more often also to support newer RN versions sooner.

**Comment by dannyBies** [comment]
That's great to hear, thanks for all the hard work and looking forward to more regular updates!
