### ISSUE TITLE
Update Required: Migrate to the Latest Firebase Integration by June 1, 2024

### ISSUE THREAD

**Issue by phuongwd** [exponea/exponea-react-native-sdk#115]
We are using the `"react-native-exponea-sdk": "^1.5.2"`
and getting this warning message

> You are using a deprecated version of the Firebase integration. Make sure you upgrade to the new Firebase integration before 1 June 2024.

<img width="315" alt="Screenshot 2024-05-07 at 14 21 15" src="https://github.com/exponea/exponea-react-native-sdk/assets/2460806/f3a837ea-f6b9-4e23-a625-985b75abe5f8">

is last version https://github.com/exponea/exponea-react-native-sdk/releases/tag/1.8.0 resolved this issue?

**Comment by adam1929** [comment]
Hi @phuongwd You need to update your Integration in Bloomreach app. SDK is compatible for this update already. Please ask support for [guidance](https://documentation.bloomreach.com/engagement/docs/firebase-webhooks)
Thank you
