### ISSUE TITLE
Incorrect NSPrivacyAccessedAPICategoryUserDefaults value in exponea-react-native-sdk causing app store rejection 

### ISSUE THREAD

**Issue by gdhillon-pbl** [exponea/exponea-react-native-sdk#117]
### Description:

When using exponea-react-native-sdk in a React Native project, the PrivacyInfo.xcprivacy file generated from the pods includes incorrect values for the NSPrivacyAccessedAPICategoryUserDefaults category. This appears to be due to incorrect values in the underlying exponea-ios-sdk.

This misreporting causes an "Invalid Binary" issue in App Store Connect, preventing successful submission.

A related issue has been reported in the exponea-ios-sdk repository: https://github.com/exponea/exponea-ios-sdk/issues/69

**Comment by gdhillon-pbl** [comment]
PR for potential fix: https://github.com/exponea/exponea-ios-sdk/pull/70

**Comment by LouisKraemer** [comment]
This should be merged and deployed quickly, it's blocking app deployment on iOS

**Comment by xcibik00** [comment]
Hi @gdhillon-pbl and @LouisKraemer, its already fixed in iOS native SDK 2.26.2 and available for RN as 1.8.1 version
