### ISSUE TITLE
Upgrade to 0.64.0

### ISSUE THREAD

**Issue by adeem** [exponea/exponea-react-native-sdk#13]
When I upgrade react native from 0.63.4 to 0.64.0. I am getting error message inside Xcode for file name: Exponea.swift

`override init() {} << 'super.init' isn't called on all paths before returning from initializer`

Take a look at the below screenshot
![Screenshot 2021-03-18 at 23 25 37](https://user-images.githubusercontent.com/68442/111705584-419d1f00-8841-11eb-958d-d9da05a989de.png)

**Comment by michaela-dev** [comment]
Hi @adeem, the new release (0.5.1), including a fix for this, is ready.  Can you please check it, and let us know? Thanks!

**Comment by tom8u4286** [comment]
Hi @michaela-dev! Sorry, do you mean the new release version of react native 0.65.1 ? Since I got the same error upgrading to 0.65. Thank you!

**Comment by michaela-dev** [comment]
No, I meant SDK version 0.5.1. Closing this issue now, if you are still facing this problem, please create a new issue. Thanks!
