### ISSUE TITLE
error: module map file ExponeaSDK_Notifications.modulemap not found

### ISSUE THREAD

**Issue by adeem** [exponea/exponea-react-native-sdk#14]
I am using latest version of exponea-react-native-sdk and enabled Rich_Push notification. When I try to archive project to create a build for App Store. I am getting following error

`<unknown>:0: error: module map file 'Xcode/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/BuildProductsPath/Release-iphoneos/ExponeaSDK-Notifications/ExponeaSDK_Notifications.modulemap' not found
<unknown>:0: error: module map file '/Intermediates.noindex/ArchiveIntermediates/BuildProductsPath/Release-iphoneos/ExponeaSDK-Notifications/ExponeaSDK_Notifications.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'`

React native version 0.63.4
Xcode 12.4

My pod file has  `platform :ios, '11.0'` when I downgrade iOS to 10.3, everything start working. What could be the reason?

Any idea?

**Comment by Igi4** [comment]
Hi @adeem, could you please try setting the iOS version to 11.0 in your XCode project settings? (It's in General -> Deployment Info section). Please change this also on the other targets, e.g. the NotificationContentExtension and NotificationServiceExtension.

Please let me know if it worked, thanks!
