### ISSUE TITLE
Compile error after upgrading to 0.5.2

### ISSUE THREAD

**Issue by hrmoller** [exponea/exponea-react-native-sdk#37]
We're experiencing compile errors after upgrading to version 0.5.2.

The `react-native-exponea-sdk` dependency is upgraded to `0.5.2` in package.json, `yarn` is executed, `pod update ExponeaSDK` is executed and finally `yarn ios` is run which results in the following error:

```
The following build commands failed:
	CompileC ~/Library/Developer/Xcode/DerivedData/client-gmsozpqlpckepzcdhiymiawljjky/Build/Intermediates.noindex/Client.build/Debug-iphonesimulator/Client.build/Objects-normal/x86_64/main.o ~/workspace/hello/client/client-app/iOS/Client/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

We have tried changing the compile settings in various ways in Xcode without any success.

We're on Mac (M1 as well as Intel)  
Xcode version 12.5.1  
React Native version 0.63.4. 
Platform version in pod file is specified to 11.0

Any help appreciated.

**Comment by Thomas0c** [comment]
This happens due to a missing update of the AppDelegate import as listed in the release notes under bug fixes: https://github.com/exponea/exponea-react-native-sdk/blob/master/documentation/RELEASE_NOTES.md#may-31-2021
