### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by PestiB9** [exponea/exponea-react-native-sdk#42]
Hi I have an error in the Android build: 

* What went wrong:
Execution failed for task ':app:mergeAppDebugAssets'.
> Could not resolve all files for configuration ':app:appDebugRuntimeClasspath'.
   > Could not find io.paperdb:paperdb:2.7.1.
     Searched in the following locations:
        ...
    Required by:
         project :app > project :react-native-exponea-sdk > com.exponea.sdk:sdk:2.9.5

In my package.json I am using the following versions:
react-native: 0.64.2
react-native-exponea-sdk: ^0.5.2

In my app/build.gradle:
    minSdkVersion = 23
    compileSdkVersion = 30
    targetSdkVersion = 30

Any idea what could be wrong?

**Comment by michaela-dev** [comment]
Please try the latest SDK version - 1.0.0, this issue could occur on previous versions where the paperDb library was used.
