### ISSUE TITLE
Exponea.setPushOpenedListener Callback not called for Push Notification based launches

### ISSUE THREAD

**Issue by sonicvision** [exponea/exponea-react-native-sdk#5]
Version    "react-native-exponea-sdk": "0.3.0",

Problem:-
When you launch the app by clicking on the notification sent from the exponea backend, it doesn't call the callback registered using Exponea.setPushOpenedListener.

Please note that once the app has been launched, and then if we again send a Push Notification, and click on it, then this call back gets called fine. Only the first App Launch part doesn't work.

Additional Note:-
I tried to debug the SDK, and I realised that in the file:- react-native-exponea-sdk/ios/Exponea+PushNotifications.swift there is a function  pushNotificationOpened, which should ideally get called when the App is opened using the Push Notification, and because this is not called, the Push is not sent to the React Native side when the listener is registered.

```
func pushNotificationOpened(
        with action: ExponeaNotificationActionType,
        value: String?,
        extraData: [AnyHashable: Any]?
    )
```

Please have a look and let me know. Also, I tried to upgrade to 0.4.0, but that fails as well, and can't build. I will post that issue in another Issue.

**Comment by wassil** [comment]
Hi,
thank you for the detailed report!
This issue has already been reported for the underlying iOS SDK, will be fixed with next release.

**Comment by sonicvision** [comment]
@wassil Thanks for your reply. Following Questions:-
1) Can you please point to the Open Github issue where the same has been reported. Couldn't find the same.
2) What is the timeline/ETA by which this would be fixed and made live?
3) I assume the fix would entail a new release of React Native SDK also. Please confirm.

**Comment by wassil** [comment]
The issue was reported internally through Exponea so there is no Github issue. 
We have the fix ready on iOS, target is end of this week to release iOS SDK and also a new version of React Native SDK 0.5.0 that will use updated iOS SDK. 
I'll ping you here once 0.5.0 is out.

**Comment by wassil** [comment]
Fixed in `0.5.0`, there is a breaking change, you have to change your iOS code a bit - a one line replace in AppDelegate.m: https://github.com/exponea/exponea-react-native-sdk/commit/621c7e210a67d6da9ac3c7d5fb824519e501c582#diff-7f95c9f12a5d5d0d5ff30f33776b1a45091af4a583a51278cfcc98cc8e23755bL31
Release notes: https://github.com/exponea/exponea-react-native-sdk/releases/tag/0.5.0

**Comment by sonicvision** [comment]
The documentation link in release notes is broken.  (iOS push notifications documentation) on this page https://github.com/exponea/exponea-react-native-sdk/releases/tag/0.5.0

**Comment by sonicvision** [comment]
Can we upgrade already?
pod install breaks.

I get the following message:-
[!] CocoaPods could not find compatible versions for pod "ExponeaSDK":
  In Podfile:
    react-native-exponea-sdk (from `../node_modules/react-native-exponea-sdk`) was resolved to 0.5.0, which depends on
      ExponeaSDK (~> 2.10.0)

None of your spec sources contain a spec satisfying the dependency: `ExponeaSDK (~> 2.10.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.

**Comment by wassil** [comment]
Yes, it's published. Just doing what pod install tells you and running `pod install --repo-update` should be enough

**Comment by sonicvision** [comment]
Finally worked with some trial and error. Will test things now.

**Comment by wassil** [comment]
Is everything working as expected?
Please close the issue if this was solved.
