### ISSUE TITLE
crash on android build v1.0.0

### ISSUE THREAD

**Issue by vnyx123** [exponea/exponea-react-native-sdk#59]
hi, could you please help with exponea sdk? I get error or maybe crash when I'm trying to run in on android
it's error for no reason and when I remove this lib my app back to normal again

**Comment by adam1929** [comment]
Hi. Please send us a stacktrace or crashlog from your app. SDK is implemented to be crash-free; so if any exception occurs inside SDK, it shows only error in logs.
Probably you may have dependency collision, that our SDK is using newer version of a library, your application an older or incompatible one. That may lead to NoSuchMethodError very easily.
