### ISSUE TITLE
iOS App Build fails on version 0.4.0

### ISSUE THREAD

**Issue by sonicvision** [exponea/exponea-react-native-sdk#6]
Hello,

I just tried to upgrade to 0.4.0, and I see the following error when trying to build the app.
Some duplicate file error.

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'react-native-exponea-sdk' from project 'Pods')
    cd /Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name react_native_exponea_sdk -Onone -enable-batch-mode -enforce-exclusivity\=checked @/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/Objects-normal/x86_64/react-native-exponea-sdk.SwiftFileList -DDEBUG -D COCOAPODS -Xcc -fmodule-map-file\=/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Products/Debug-iphonesimulator/ExponeaSDK/ExponeaSDK.modulemap -Xcc -fmodule-map-file\=/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/yoga/Yoga.modulemap -import-underlying-module -Xcc -fmodule-map-file\=/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/react_native_exponea_sdk/react-native-exponea-sdk.modulemap -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk -target x86_64-apple-ios10.3-simulator -g -module-cache-path /Users/psahu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Index/DataStore -swift-version 5 -I /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Products/Debug-iphonesimulator/react-native-exponea-sdk -I /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Products/Debug-iphonesimulator/ExponeaSDK -F /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Products/Debug-iphonesimulator/react-native-exponea-sdk -c -j12 -output-file-map /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/Objects-normal/x86_64/react-native-exponea-sdk-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/Objects-normal/x86_64/react_native_exponea_sdk.swiftmodule -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/react-native-exponea-sdk-generated-files.hmap -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/react-native-exponea-sdk-own-target-headers.hmap -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/react-native-exponea-sdk-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/react-native-exponea-sdk-project-headers.hmap -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Products/Debug-iphonesimulator/react-native-exponea-sdk/include -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Private -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Private/react-native-exponea-sdk -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/DoubleConversion -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/FBLazyVector -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/FBReactNativeSpec -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/RCTRequired -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/RCTTypeSafety -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-Core -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-RCTText -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-callinvoker -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-cxxreact -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-jsi -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-jsiexecutor -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/React-jsinspector -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/ReactCommon -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/Yoga -Xcc -I/Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods/Headers/Public/glog -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/DerivedSources-normal/x86_64 -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/DerivedSources/x86_64 -Xcc -I/Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG\=1 -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -emit-objc-header -emit-objc-header-path /Users/psahu/Library/Developer/Xcode/DerivedData/Raisin-eurzduqfjbrjxpfuyagtktzbcdow/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-exponea-sdk.build/Objects-normal/x86_64/react_native_exponea_sdk-Swift.h -working-directory /Users/psahu/Documents/Workspace/raisin-mobile/ios/Pods

<unknown>:0: error: filename "Exponea.swift" used twice: '/Users/psahu/Documents/Workspace/raisin-mobile/node_modules/react-native-exponea-sdk/ios/Exponea.swift' and '/Users/psahu/Documents/Workspace/raisin-mobile/node_modules/react-native-exponea-sdk/ios/Pods/ExponeaSDK/ExponeaSDK/ExponeaSDK-Shared/Exponea.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "ExponeaError.swift" used twice: '/Users/psahu/Documents/Workspace/raisin-mobile/node_modules/react-native-exponea-sdk/ios/ExponeaError.swift' and '/Users/psahu/Documents/Workspace/raisin-mobile/node_modules/react-native-exponea-sdk/ios/Pods/ExponeaSDK/ExponeaSDK/ExponeaSDK-Shared/ExponeaError.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command CompileSwiftSources failed with a nonzero exit code

**Comment by wassil** [comment]
Looks like I messed up the release of 0.4.0 and the package contains development pods. I'll release 0.4.1 that will be the same as 0.4.0(just working ;)) and deprecate 0.4.0

**Comment by wassil** [comment]
0.4.1 is out, seems to fix both this and the other reported issue with super long pod install output.
I'll close this, reopen if you still have issues.
