### ISSUE TITLE
Android crashes with IllegalArgumentException 

### ISSUE THREAD

**Issue by tr3v3r** [exponea/exponea-react-native-sdk#67]
**We are facing crashes on production on Android.** 
The issue appears  on App start

**Error and stack trace:**
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/23724142/191716128-24efc082-c124-44d3-8dd1-44e6b1e2dcad.png">

The error thrown by the request method from '[NetworkHandlerImpl.kt](https://github.com/exponea/exponea-android-sdk/blob/develop/sdk/src/main/java/com/exponea/sdk/network/NetworkHandlerImpl.kt)' in exponea android-sdk.

The issues connected with okhttp packages for Android. [This ](https://github.com/square/okhttp/pull/1674/files)is related PR with an explanation.

**Additional info:**

"react-native-exponea-sdk": "1.0.0"
"react-native": "0.67.3"

**I've followed the steps in the stack trace and realized that URL is broken in :**
<img width="674" alt="image" src="https://user-images.githubusercontent.com/23724142/191717067-31048c8d-4479-4b6f-a227-8e4fc977464e.png">

[FlushManagerImpl.kt](https://github.com/exponea/exponea-android-sdk/blob/922ffa6c719145d2f3e49b0706e03f9ff103376e/sdk/src/main/java/com/exponea/sdk/manager/FlushManagerImpl.kt#L55)

**Comment by adam1929** [comment]
Hi @tr3v3r thank you for your report. I'm just hoping to ask for value for that broken URL you mentioned, but do not send it if it 'critical info' for you. I would like to see what is bad in URL at all.
Back to problem. There is no catching of any technical exception according to broken URL or so. SDK is naively thinking of correct setup of baseUrl and project token (only dynamic part of URL that may cause problem). So there is no comprehensive check of configuration possibilities.
Please, am I in correct thinking of that problem? Is there some advise from you, what you would expect in this case? Thank you.

**Comment by xcibik00** [comment]
Closed due inactivity

**Comment by ViktorOsadchyi** [comment]
@adam1929 We have static baseUrl. Our baseUrl is https://exponea-api.<our domain>
Also I see that the crash appears not only on App start.

Sorry, I don't have any more information yet.
