### ISSUE TITLE
Support Xcode 14, iOS 16

### ISSUE THREAD

**Issue by andreilupu-plt** [exponea/exponea-react-native-sdk#68]
IDE: Xcode 14
OS: iOS 16
Library version: 1.1.0

We have a problem when we are trying to compile the app on iOS. The problem is related to your  [exponea-ios-sdk](https://github.com/exponea/exponea-ios-sdk/tree/develop/ExponeaSDK) dependency. That library had a problem with `WKPreferences > isElementFullscreenEnabled` property which is available since `iOS 15.4` and they had set `iOS 15.0` ([here you can see the issue](https://github.com/exponea/exponea-ios-sdk/issues/37) & [here you can see the code](https://github.com/exponea/exponea-ios-sdk/blob/895ef0ece16786cedf5046bd653007335bf66191/ExponeaSDK/ExponeaSDK/Classes/InAppMessages/View/InAppMessageWebView.swift#L94))

They fixed the problem into the latest release `2.12.3` but your latest release `1.1.0` has as dependency `2.12.1` [here you can see your dependency](https://github.com/exponea/exponea-react-native-sdk/blob/8069b7b0b48b997418fe7723da1e0006e85d3e48/ios/Podfile#L14) 

So, can you please update your `exponea-ios-sdk` dependency?

<img width="1139" alt="image (3)" src="https://user-images.githubusercontent.com/92313678/192755182-656aae02-62e2-405f-a5a9-dd7dcf1b088b.png">

**Comment by andreilupu-plt** [comment]
Thank you @xcibik00 . Do you have any idea when this fix will be available? In the meantime we have to find a workaround.

**Comment by adam1929** [comment]
@andreilupu-plt please use RN build 1.1.1, it should help you with that.
Yes there were some misinterpreting of changes in iOS apple SDK = Apples older Swift API docs were saying 15.0 support for that field but latest API is telling 15.4 :-/ 
Latest RN 1.1.1 should be fine for you
