### ISSUE TITLE
Lib directory is missing on package install 

### ISSUE THREAD

**Issue by andreilupu-plt** [exponea/exponea-react-native-sdk#69]
Library version: 1.1.1

When we are trying to install the latest library version the library is installed correctly but the `lib` directory with the javascript files is missing.

P.S. We tried to install it into a new project and we had same error.

Steps to replicate it:
```
$ mkdir testExponea
$ cd testExponea
$ yarn add react-native-exponea-sdk
$ ls -al node_modules/react-native-exponea-sdk
```

you will see that the `lib` directory is missing in contrast with `1.1.0` version

**Previous version (1.1.0)**

<img width="945" alt="Screenshot 2022-10-11 at 16 47 26" src="https://user-images.githubusercontent.com/92313678/195138936-e7a360f7-a96a-483a-9ccb-9b01a1e8e917.png">

**Current version (1.1.1)**
<img width="966" alt="Screenshot 2022-10-11 at 16 48 50" src="https://user-images.githubusercontent.com/92313678/195139317-a6230aee-5dce-4191-8d10-a29b25677487.png">

**Comment by adam1929** [comment]
@andreilupu-plt Thank you for your found. Our build flow failed but it has been published anyway :-O we fix that and now a new hot-release is available 1.1.1-1. It still contains version 1.1.1 under hood, but is builded correctly.
