### ISSUE TITLE
pod install shows weird logs on upgrading to 0.4.0

### ISSUE THREAD

**Issue by sonicvision** [exponea/exponea-react-native-sdk#7]
Hello, 
I just raised another issue to highlight the fact that the iOS build fails with 0.4.0.

Other than that I see some extremely long logs when I do pod install after upgrading to 0.4.0 in my package.json

The logs looks like the below.. (only pasting first and last few lines, as it is super long)

-----------------------
Generating Pods project
Integrating client project
Pod installation complete! There are 97 dependencies from the Podfile and 108 total pods installed.

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXBuildFile -- Pods.xcodeproj/targets/buildConfigurationList:buildConfigurations:baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,defaultConfigurationIsVisible:0,defaultConfigurationName:Release,displayName:ConfigurationList,isa:XCConfigurationList,,buildPhases:buildActionMask:2147483647,displayName:Headers,files:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,isa:PBXHeadersBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:Sources,files:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,isa:PBXSourcesBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:Frameworks,files:,isa:PBXFrameworksBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:Copy generated compatibility header,files:,inputFileListPaths:,inputPaths:|,|,|,isa:PBXShellScriptBuildPhase,name:Copy generated compatibility header,outputFileListPaths:,outputPaths:|,|,|,runOnlyForDeploymentPostprocessing:0,shellPath:/bin/sh,shellScript:COMPATIBILITY_HEADER_PATH="${BUILT_PRODUCTS_DIR}/Swift Compatibility Header/${PRODUCT_MODULE_NAME}-Swift.h"
MODULE_MAP_PATH="${BUILT_PRODUCTS_DIR}/${PRODUCT_MODULE_NAME}.modulemap"

ditto "${DERIVED_SOURCES_DIR}/${PRODUCT_MODULE_NAME}-Swift.h" "${COMPATIBILITY_HEADER_PATH}"
ditto "${PODS_ROOT}/Headers/Public/react_native_exponea_sdk/react-native-exponea-sdk.modulemap" "${MODULE_MAP_PATH}"
ditto "${PODS_ROOT}/Headers/Public/react_native_exponea_sdk/react-native-exponea-sdk-umbrella.h" "${BUILT_PRODUCTS_DIR}"
printf "\n\nmodule ${PRODUCT_MODULE_NAME}.Swift {\n  header \"${COMPATIBILITY_HEADER_PATH}\"\n  requires objc\n}\n" >> "${MODULE_MAP_PATH}"
,,buildRules:,dependencies:displayName:React,isa:PBXTargetDependency,targetProxy:containerPortal:|,displayName:|,isa:|,proxyType:|,remoteGlobalIDString:|,remoteInfo:|,,,displayName:ExponeaSDK,isa:PBXTargetDependency,targetProxy:containerPortal:|,displayName:|,isa:|,proxyType:|,remoteGlobalIDString:|,remoteInfo:|,,,displayName:react-native-exponea-sdk,isa:PBXNativeTarget,name:react-native-exponea-sdk,packageProductDependencies:,productName:react-native-exponea-sdk,productReference:displayName:libreact-native-exponea-sdk.a,explicitFileType:archive.ar,includeInIndex:0,isa:PBXFileReference,name:libreact-native-exponea-sdk.a,path:libreact-native-exponea-sdk.a,sourceTree:BUILT_PRODUCTS_DIR,,productType:com.apple.product-type.library.static,/buildPhases/buildActionMask:2147483647,displayName:Sources,files:displayName:Exponea.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:ExponeaAppDelegate.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:objc_tryCatch.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:CwlCatchException.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:CwlMachBadInstructionHandler.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:mach_excServer.c,fileRef:displayName:|,includeInIndex:|,isa:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:DSL.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:NMBExceptionCapture.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:NMBStringify.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:XCTestObservationCenter+Register.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:QuickSpecBase.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:QuickConfiguration.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:QCKDSL.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:QuickSpec.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:XCTestSuite+QuickTestSuiteBuilder.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:DoubleConversion-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:ExponeaSDK-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:FBReactNativeSpec-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:Folly-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:glog-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:Nimble-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:Pods-Exponea-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:Pods-Tests-dummy.m,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourc

-----to the end----

me:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Uri.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:UTF8String.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Utility.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Varint.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:VirtualExecutor.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:commandlineflags.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:googleinit.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:mutex.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:config.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:config_for_unittests.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:demangle.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:logging.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:log_severity.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:raw_logging.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stl_logging.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:vlog_is_on.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:googletest.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:mock-log.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stacktrace.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stacktrace_generic-inl.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stacktrace_libunwind-inl.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stacktrace_powerpc-inl.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stacktrace_x86-inl.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:stacktrace_x86_64-inl.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:symbolize.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:utilities.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:CwlCatchException.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:CwlMachBadInstructionHandler.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:mach_excServer.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:CwlPreconditionTesting.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Nimble.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:DSL.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:NMBExceptionCapture.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:NMBStringify.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:QuickSpecBase.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:QuickConfiguration.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:QCKDSL.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Quick.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:QuickSpec.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:ExponeaSDK-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Nimble-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Pods-Exponea-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Pods-Tests-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:Quick-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:react-native-exponea-sdk-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,isa:PBXHeadersBuildPhase,runOnlyForDeploymentPostprocessing:0,/files/displayName:String.h,fileRef:displayName:String.h,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:sourcecode.c.h,path:String.h,sourceTree:<group>,,isa:PBXBuildFile,settings:ATTRIBUTES:Project,,

**Comment by wassil** [comment]
0.4.0 is a bad release that has been deprecated.
0.4.1 fixes this issue.
