### ISSUE TITLE
Update documentation for upgrading version from 0.x.x to 1.x.x 

### ISSUE THREAD

**Issue by adeem** [exponea/exponea-react-native-sdk#71]
First of all thanks for this documentation. When I try to follow the steps, I started to get following error
```
app/MessageService.java:5: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessagingService;  
```

So basically one step which needs to be added is, please add `implementation 'com.google.firebase:firebase-messaging:15.0.2'` in android/app/build.gradle `dependencies` 

https://github.com/exponea/exponea-react-native-sdk/blob/develop/documentation/VERSION_UPDATE.md

**Comment by adam1929** [comment]
Thank you, nice catch !
