### ISSUE TITLE
Huawei pushes not working

### ISSUE THREAD

**Issue by pe1ros** [exponea/exponea-react-native-sdk#73]
Hello!
I did all steps describes in your tutorial. But pushes not work on Huawei devices

**Comment by pe1ros** [comment]
[this guideline](https://github.com/exponea/exponea-react-native-sdk/blob/master/documentation/PUSH_ANDROID.md) have some mistakes from your  [Example folder](https://github.com/exponea/exponea-react-native-sdk/tree/master/example/android/app/src) also [Native Android implementation](https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/PUSH.md) have another description, but as you write RN sdk just wrapper around Native Android/iOS SDK

**Comment by adam1929** [comment]
@pe1ros Thank you for findings. We'll fix guideline.
