### ISSUE TITLE
Push notifications not playing default sound

### ISSUE THREAD

**Issue by karel-suchomel-ed** [exponea/exponea-react-native-sdk#74]
I am facing an issue where push notifications successfully arrive to the user, but no default OS notification sound is played.
Notifications themselves work fine and the phone is not in silent mode. Is any additional setup needed, to make the default OS sound work?

**Comment by adam1929** [comment]
Hi @karel-suchomel-ed please check payload of your Push.
There should be
```
{
    "to" : "DEVICE-TOKEN",
    "notification" : {
      "body"  : "NOTIFICATION BODY",
      "title" : "NOTIFICATION TITILE",
      "sound" : "default"
    }
  }
````
"default" value in sound.

**Comment by karel-suchomel-ed** [comment]
Hi @adam1929 thank you for your feedback, unfortunately, the issue still persists. I'm testing notifications through the Bloomreach admin and even if I specify the sound parameter as "default" I still don't get any sound or vibration.

This is what it looks like in a builder:

```
{
    "title": "Notification title",
    "action": "app",
    "actions": [],
    "message": "Message",
    "sound": "default"
}
```

**Comment by sushilsharma06** [comment]
@adam1929  I am facing the same issue. Triggering notification from bloomreach dashboard and setting sound to default.
My payload looks like this. But still no notification sound in iOS.

{
    action = deeplink;
    aps =     {
        alert =         {
            body = "test push";
            title = "Notification title";
        };
        "mutable-content" = 1;
    };
    sound = default;
};

**Comment by adam1929** [comment]
Hi @karel-suchomel-ed is this issue still occuring?
Your notification data payload seems valid. We are not able to reproduce issue. There could be another limitation given by system especially for notification importance: https://developer.android.com/develop/ui/views/notifications#importance
If issue peersists, please contact support with application logs.
Thank you

**Comment by adam1929** [comment]
Hi @karel-suchomel-ed were you able to simulate issue on latest SDK? Or did you contact support? Thank you

**Comment by karel-suchomel** [comment]
HI @adam1929 i missed the first message sorry. It is resolved and working, I managed to fix it back then but I don't remember what was the cause :D
