### ISSUE TITLE
Exponea.isConfigured() in android always returns true after first launch

### ISSUE THREAD

**Issue by mohammadalijf** [exponea/exponea-react-native-sdk#75]
base on documentation we have a code as below 

```typescript
const configureExponea = async (
  configuration: Configuration
): Promise<boolean> => {
  try {
    const isConfigured = await Exponea.isConfigured();
    console.log({ isConfigured });
    if (isConfigured) {
      return true;
    }
    await Exponea.configure(configuration);
    return true;
  } catch (error) {
    console.error(error);
    return false;
  }
};
```
Only in Android we have a problem:

In first launch of the app `isConfigured` return false which is correct and we configure the exponea. but when we kill the app completely and run it again, isConfigured will always return true which is different behaviour from iOS. is this expected behaviour?

**Comment by adam1929** [comment]
Hi @mohammadalijf. SDK running on Android is able to auto-initialise itself. It means that if SDK has been configured previously, it will be initialised from that config in case of invoking of:

- `handleNewToken`
- `handleNewHmsToken`
- `handleRemoteMessage`
- or app is opened by clicked push notification (app is starting with Intent Action com.exponea.sdk.action.PUSH_[URL_|DEEPLINK_]CLICKED

This behaviour is not implemented in iOS build.
