### ISSUE TITLE
Does the Exponea React Native SDK support Tracking Universal Linking

### ISSUE THREAD

**Issue by sonicvision** [exponea/exponea-react-native-sdk#8]
Hello,
We are using Universal Link in our react native app. Just want to make sure that the tracking of Universal Linking works in the app.
I don't see any documentation for the same in the React Native SDK. Though I can see the same in the iOS SDK https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/UNIVERSAL_LINK.md#-tracking-universal-links

Can you please confirm what needs to be done in the case of implementing Universal Linking on the react native side?

**Comment by wassil** [comment]
Hi,
that's actually the last functionality that's available in native SDKs and missing in react native. 
It's currently worked on and will be available in the next version(ETA end of this week)

**Comment by sonicvision** [comment]
Thanks Wassil,
Do you have any pointers how to do this tracking on the website. Once the universal linking would come in, the app side tracking will be using the RN SDK. But, what about the website part of tracking? Any clue or pointers regarding the same would be helpful.

**Comment by wassil** [comment]
I'm not really sure, I don't have much experience with Exponea JS SDK. 
I briefly checked the documentation(https://docs.exponea.com/docs/tracking) but did not find a function that would do it.
I would ask your Exponea representative, they'll find the right person to answer this.

**Comment by wassil** [comment]
I've just released `0.5.0` that supports universal links/app links.
Related doc: https://github.com/exponea/exponea-react-native-sdk/blob/master/documentation/LINKING.md
Commit that sets it up for our example app: https://github.com/exponea/exponea-react-native-sdk/commit/788ee2fa8ce565a13dcc0c1dcb727d8a97c96aae
