### ISSUE TITLE
Versions below react-native 0.70 not being supported anymore?

### ISSUE THREAD

**Issue by jangsoori** [exponea/exponea-react-native-sdk#80]
Hey,

In the newest version of the SDK, there is a peer dependency lock for `react@^18.1.0`

Because of this, we can't install the SDK on `react-native@0.69.6` which uses `react@18.0.0`. `react@18.1.0` was introduced in `react-native@0.70.0`, so does it mean that anything below `react-native@0.70` is not supported by the SDK anymore?

```
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.1.0" from react-native-exponea-sdk@1.2.0
```

Thanks!

**Comment by adam1929** [comment]
Hi @jangsoori 
please do update to RN 0.70 or later (depends on current SDK dependency tree)
React 18+ should be compatible with react69 as docs says: https://reactnative.dev/docs/0.70/react-18-and-react-native
Please see note that RN70 is not maintained, so try update your app to active RN version.
