### ISSUE TITLE
Not able to build Android app with react-native-exponea-sdk veriosn 15

### ISSUE THREAD

**Issue by Vinanti-Pansari** [exponea/exponea-react-native-sdk#88]
here is the error, that I am getting after upgrading Exponea SDK version ( this issue is related to Android only)

I have tried with react native version 0.70.6 and 0.71.8, but the same issue I am facing. (node verion: 18.7.0)

This issue is on priority, waiting for the quick reply to fix this issue

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDevelopmentDebug -PreactNativeDevServerPort=8081
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/appPath/node_modules/react-native-exponea-sdk/src'
    at Object.lstatSync (node:fs:1574:3)
    at /appPath/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:75:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/appPath/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:74:10)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/appPath/node_modules/react-native-exponea-sdk/src'
}

**Comment by frenic** [comment]
This patch seems to solve it:

```patch
diff --git a/node_modules/react-native-exponea-sdk/package.json b/node_modules/react-native-exponea-sdk/package.json
index bb05dd6..81dece0 100644
--- a/node_modules/react-native-exponea-sdk/package.json
+++ b/node_modules/react-native-exponea-sdk/package.json
@@ -76,13 +76,5 @@
         "react"
       ]
     }
-  },
-  "codegenConfig": {
-    "name": "example",
-    "type": "all",
-    "jsSrcsDir": "src",
-    "android": {
-      "javaPackageName": "com.exponea"
-    }
   }
 }

**Comment by Vinanti-Pansari** [comment]
@frenic, is this worked for you?

**Comment by frenic** [comment]
Yes, it works for me

**Comment by Vinanti-Pansari** [comment]
Thanks @frenic :)
I am on RN version 0.70.6 and for this version this patch file works for me
diff --git a/node_modules/react-native-exponea-sdk/android/build.gradle b/node_modules/react-native-exponea-sdk/android/build.gradle
index 272f6ad..499b2ca 100644
--- a/node_modules/react-native-exponea-sdk/android/build.gradle
+++ b/node_modules/react-native-exponea-sdk/android/build.gradle
@@ -93,7 +93,7 @@ repositories {
 dependencies {
     implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
     //noinspection GradleDynamicVersion
-    implementation "com.facebook.react:react-android:0.71.8"
+    implementation "com.facebook.react:react-native:+"
     implementation 'com.exponea.sdk:sdk:3.6.1'
     implementation 'com.google.code.gson:gson:2.8.9'
     implementation 'org.danilopianini:gson-extras:0.2.2'
diff --git a/node_modules/react-native-exponea-sdk/package.json b/node_modules/react-native-exponea-sdk/package.json
index bb05dd6..81dece0 100644
--- a/node_modules/react-native-exponea-sdk/package.json
+++ b/node_modules/react-native-exponea-sdk/package.json
@@ -76,13 +76,5 @@
         "react"
       ]
     }
-  },
-  "codegenConfig": {
-    "name": "example",
-    "type": "all",
-    "jsSrcsDir": "src",
-    "android": {
-      "javaPackageName": "com.exponea"
-    }
   }
 }

for creating this patch I excluded all things apart from the required one
yarn patch-package --exclude 'android/build/' react-native-exponea-sdk

**Comment by frenic** [comment]
Well, it should be permanently fixed as well @adam1929 @Vinanti-Pansari  so perhaps this should be opened again?

**Comment by adam1929** [comment]
Thanks @frenic for patch, we removed this part, is in 1.5.1.
This codegenConfig has been added by RN migration tool for 0.70.6. I removed it, it has no (negative) impact on build process. We are using YARN do build app, maybe it handle it correctly.
