### ISSUE TITLE
Use ~0.71.0 as peer dependency

### ISSUE THREAD

**Issue by frenic** [exponea/exponea-react-native-sdk#89]
What is the reason you're using `<=` for `react-native` as peer dependency? `<=0.71.8` prevents us from upgrading to `0.71.9` and `0.71.10`. Is it possible to use `~0.71.0` as peer dependency for `react-native` instead so we're allowed to upgrade patch upgrades, that are usually stability fixes.

**Comment by adam1929** [comment]
Hi @frenic thank you for note. This rule has its intended purpose - we are not able to guarantee that SDK will work in 0.71.9.
Frankly, it should, but from our XP there were changes in RN (I think 0.70.2->3) that were not compatible for previous build process. Same issue may appear for 0.71.9, we are not able to tell.
I got your point, for next RN update, you need to wait until SDK will be released too :-/

**Comment by frenic** [comment]
Okay, but can you at least verify React Native patch releases as soon as possible and bump peer dependency if no issues occur? Exponea is usually the only package blocking us from React Native upgrades, because `npm install` will exit with an error. And blocking us from React Native patch updates are quite often crucial.
