### ISSUE TITLE
"Open web browser" type notification also opens the app in iOS

### ISSUE THREAD

**Issue by kaystd** [exponea/exponea-react-native-sdk#9]
Hello!
Notification with type "Open web browser" opens the app first and than opens the link in browser in iOS 14.3.

**Comment by wassil** [comment]
Hi, as far as I know it's not even possible to open browser directly from a push notification on iOS. 
We have to first the app and process the push there, that's how this works on any iOS version.

**Comment by kaystd** [comment]
Thanks for the answer!
