### ISSUE TITLE
Notifications are not deleted on time (Android)

### ISSUE THREAD

**Issue by Vinanti-Pansari** [exponea/exponea-react-native-sdk#93]
On the Exponea dashboard whatever expiration, we set for deleting the Push notification. It is taking time more than  the time we have set

Exponea version: 1.5.1
<img width="874" alt="Screenshot 2023-06-21 at 9 58 20 AM" src="https://github.com/exponea/exponea-react-native-sdk/assets/54045800/71f32131-20d6-4f9b-b31f-97238c941acf">

**Comment by adam1929** [comment]
Hi @Vinanti-Pansari thank you for findings, we'll bring fix for this issue. App Inbox message stays in local storage even it has been removed from BE. Please call identifyCustomer() more frequently for now, it will refresh your app inbox messages.
