### ISSUE TITLE
AppInbox resolution issue on tablet device

### ISSUE THREAD

**Issue by ivayloivan0v** [exponea/exponea-react-native-sdk#94]
Hello,
I'm trying to setup the App Inbox in a react native project and everything went smooth until I tested it on tablet.
Case flow: 
- Open App Inbox
- Click on Push Notification
When I open a Push Notification from the App Inbox the resolution of the image in the modal is huge. I've tried adding a much smaller image (16x16) and it's still spreading it. I've been looking for some properties from which I can control the size of the image but couldn't find any. Please advise if there is a way to fix that.
Attached is a screenshot of the issue.
<img width="808" alt="Screenshot 2023-07-21 at 13 38 29" src="https://github.com/exponea/exponea-react-native-sdk/assets/105466645/0c97efd9-4a32-40b4-b953-7dfb64c77cdb">
<img width="784" alt="Screenshot 2023-07-21 at 13 38 47" src="https://github.com/exponea/exponea-react-native-sdk/assets/105466645/71319cfb-1500-4580-afc1-87d01f9f34f0">

**Comment by adam1929** [comment]
Hi @ivayloivan0v thank you for reporting. This image is handled 'natively' by UIImageView with contentMode = .scaleAspectFill (is: `contents scaled to fill with fixed aspect. some portion of content may be clipped.`)
We check it in iOS, how it could be done more dynamic.
Meanwhile you have some options here:
1. Provide image that will fit `fill` behaviour. Maybe your image (Thund... Thursd...) has ultra-wide proportions, ImageView scales image to fit its height but it results into large width.
2. Try to register own AppInboxProvider (needs to be in swift) https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/APP_INBOX.md#ui-components-styling and modify that view by `getAppInboxDetailViewController`
3. use HTML app inbox message

**Comment by xcibik00** [comment]
Hi @ivayloivan0v - fixed in new SDK v1.6.0
