### ISSUE TITLE
Update documentation for installation event

### ISSUE THREAD

**Issue by petgus-lyko** [exponea/exponea-react-native-sdk#97]
https://github.com/exponea/exponea-react-native-sdk/blob/master/documentation/TRACKING.md
It would be nice to mention in the documentation the effect a anonymisation has on the installation event. 

We saw a scenario where a users would have several installation events with only a day or two apart.
Turns out that an installation event will be tracked again if the user was anonymised.

We anonymise users when they logout of the app, hence they will get a new installation event when logging in again.

**Comment by adam1929** [comment]
Thank you @petgus-lyko 
Yes it may help to understand these "anomalies" better.
