### ISSUE TITLE
Support for react native 0.72.x

### ISSUE THREAD

**Issue by jangsoori** [exponea/exponea-react-native-sdk#98]
Hi, react native 0.72 was released a while ago and with 0.73 RC released, is there any plans in the near future to update SDK to allow it on 0.72 without hacking peer dependencies?

```json
  "peerDependencies": {
    "react": "^17.0.2 || ^18.0.0",
    "react-native": "<=0.71.8"
  },
```

**Comment by xcibik00** [comment]
Hi @jangsoori , will be updated in new version of Exponea RN SDK

**Comment by karel-suchomel-ed** [comment]
When is the new update coming out? RN 0.71 has a bunch of issues, that are solved with newer releases and I would love to update already

**Comment by xcibik00** [comment]
Hi @karel-suchomel-ed , we are currently working on new version of React Native SDK -> should be available during next week.
