### ISSUE TITLE
Support for In-app content blocks

### ISSUE THREAD

**Issue by StuartPyper** [exponea/exponea-react-native-sdk#99]
Can you please add support for in-app content blocks: 
https://documentation.bloomreach.com/engagement/docs/in-app-content-blocks

I can see that it has been added to the two native SDKs but not to the react native one:
https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/IN_APP_CONTENT_BLOCKS.md
https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/IN_APP_CONTENT_BLOCKS.md 

Thanks.

**Comment by xcibik00** [comment]
Hi @StuartPyper , thank you for your request, yes currently its only supported in native SDKs but we are working on the support also for RN - should be a part of next RN version.

**Comment by StuartPyper** [comment]
That's great, thanks. 
I've been asked to check if you have a target date for the next release?

**Comment by xcibik00** [comment]
Hi @StuartPyper new RN version 1.6.0 is already available, with support of In-app content blocks
